version: "3"
services:
  cms-composer:
    build:
      context: ./cms-composer
      dockerfile: Dockerfile.development
    restart: always
    ports:
      - "7781:7781"
    environment:
      - UI_URL=http://localhost:5173
      - CMS_MONGODB_URI=mongodb://root:pass@mongo:27017/linksaver?authSource=admin
      - CMS_DB_NAME=linksaver
    depends_on:
      - mongo
    volumes:
      - ./cms-composer/src:/usr/app/src
    working_dir: /usr/app/src

  cms-renderer:
    build:
      context: ./cms-renderer
      dockerfile: Dockerfile.development
    restart: always
    ports:
      - "7782:7782"
    environment:
      - UI_URL=http://localhost:5173
      - CMS_MONGODB_URI=mongodb://root:pass@mongo:27017/linksaver?authSource=admin
      - CMS_DB_NAME=linksaver
    depends_on:
      - mongo
    volumes:
      - ./cms-renderer/src:/usr/app/src
    working_dir: /usr/app/src

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=linksaver
    ports:
      - "27018:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8089:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://root:pass@mongo:27017/
      ME_CONFIG_BASICAUTH: false
